name: Main

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "v21.7.3"

      - name: Install dependencies
        run: npm install

      - name: Run tests (only for dev branch)
        run: |
          if [ ${{ github.ref }} == 'refs/heads/dev' ]; then
            npm test
          else
            echo "Skipping tests on branch ${{ github.ref }}"
          fi
